services:
  db:
    image: postgres:16
    container_name: order-manager-db
    environment:
      POSTGRES_USER: order_user
      POSTGRES_PASSWORD: order_pass
      POSTGRES_DB: order_manager
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U order_user -d order_manager" ]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - order-manager-net

volumes:
  postgres_data:

networks:
  order-manager-net:
    external: true
